env:
  browser: true
  es2021: true
  node: true
extends:
  - "eslint:recommended"
  - "plugin:react/recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:prettier/recommended"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - "@typescript-eslint"
  - simple-import-sort
rules:
  {
    "react/prop-types": "off",
    "simple-import-sort/exports": "error",
    "simple-import-sort/imports": "error",
  }
settings:
  react:
    version: "detect"
