env:
  browser: true
  es2020: true
  node: true
extends:
  - "eslint:recommended"
  - "plugin:react/recommended"
  - "plugin:@typescript-eslint/recommended"
  - "prettier/@typescript-eslint"
  - "plugin:prettier/recommended"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - "@typescript-eslint"
  - import
ignorePatterns:
  - registerServiceWorker.ts
  - "*.js"
rules: { "react/prop-types": "off", "import/order": "error" }
settings:
  react:
    version: "detect"
